"""matriculas, horarios fixos e blackouts

Revision ID: 42f493470451
Revises: 8e6f53d3126d
Create Date: 2026-09-09 22:36:58.643856

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "42f493470451"
down_revision: str | None = "8e6f53d3126d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blackouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=False),
        sa.Column("data_fim", sa.Date(), nullable=False),
        sa.Column("motivo", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("data_fim >= data_inicio", name=op.f("ck_blackouts_periodo_coerente")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blackouts")),
    )
    op.create_index("ix_blackouts_periodo", "blackouts", ["data_inicio", "data_fim"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ativa",
                "suspensa",
                "encerrada",
                name="statusmatricula",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("vigencia_inicio", sa.Date(), nullable=False),
        sa.Column("vigencia_fim", sa.Date(), nullable=True),
        sa.Column("valor_mensal_centavos", sa.Integer(), nullable=False),
        sa.Column("dia_vencimento", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valor_mensal_centavos >= 0", name=op.f("ck_enrollments_valor_nao_negativo")
        ),
        sa.CheckConstraint(
            "vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio",
            name=op.f("ck_enrollments_vigencia_coerente"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_enrollments_patient_id_patients")
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"], ["users.id"], name=op.f("fk_enrollments_professional_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_enrollments_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
    )
    op.create_index(
        "ix_enrollments_paciente", "enrollments", ["patient_id", "status"], unique=False
    )
    op.create_table(
        "enrollment_horarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("dia_semana", sa.SmallInteger(), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dia_semana BETWEEN 0 AND 6", name=op.f("ck_enrollment_horarios_dia_semana_valido")
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_enrollment_horarios_enrollment_id_enrollments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_horarios")),
    )
    op.create_index(
        "ix_enrollment_horarios_slot",
        "enrollment_horarios",
        ["dia_semana", "hora_inicio"],
        unique=False,
    )
    op.create_index(
        "ix_enrollment_horarios_unico",
        "enrollment_horarios",
        ["enrollment_id", "dia_semana", "hora_inicio"],
        unique=True,
    )
    op.add_column("bookings", sa.Column("enrollment_id", sa.Integer(), nullable=True))
    # Ajuste manual: o autogenerate NÃO detecta CheckConstraint adicionado a
    # tabela existente. Sem esta linha, a regra "uma reserva pertence a no
    # máximo um contrato" viveria só no model e nunca chegaria ao banco.
    op.create_check_constraint(
        "um_contrato_no_maximo",
        "bookings",
        "enrollment_id IS NULL OR package_id IS NULL",
    )
    op.create_index(
        "ix_bookings_matricula_por_sessao",
        "bookings",
        ["enrollment_id", "session_id"],
        unique=True,
        postgresql_where=sa.text("enrollment_id IS NOT NULL AND status <> 'cancelada'"),
    )
    op.create_foreign_key(
        op.f("fk_bookings_enrollment_id_enrollments"),
        "bookings",
        "enrollments",
        ["enrollment_id"],
        ["id"],
    )
    op.add_column(
        "configuracao",
        sa.Column(
            "janela_reposicao",
            sa.Enum(
                "mes_calendario",
                "ciclo_do_paciente",
                "sem_prazo",
                name="janelareposicao",
                native_enum=False,
                length=32,
            ),
            nullable=False,
            # Ajuste manual: a tabela já tem a linha única de configuração.
            # Coluna NOT NULL sem default falharia no upgrade de um banco em
            # uso. O default fica só no DDL — o model continua definindo o
            # padrão para linhas novas.
            server_default="mes_calendario",
        ),
    )
    op.drop_column("configuracao", "reposicao_prazo_mesmo_mes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuracao",
        # Ajuste manual: mesmo motivo, no sentido inverso.
        sa.Column(
            "reposicao_prazo_mesmo_mes",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.drop_column("configuracao", "janela_reposicao")
    # op.f() impede que a convenção de nomes prefixe "ck_bookings_" de novo,
    # gerando "ck_bookings_ck_bookings_...". Erro real, pego ao rodar o ciclo.
    op.drop_constraint(op.f("ck_bookings_um_contrato_no_maximo"), "bookings", type_="check")
    op.drop_constraint(
        op.f("fk_bookings_enrollment_id_enrollments"), "bookings", type_="foreignkey"
    )
    op.drop_index(
        "ix_bookings_matricula_por_sessao",
        table_name="bookings",
        postgresql_where=sa.text("enrollment_id IS NOT NULL AND status <> 'cancelada'"),
    )
    op.drop_column("bookings", "enrollment_id")
    op.drop_index("ix_enrollment_horarios_unico", table_name="enrollment_horarios")
    op.drop_index("ix_enrollment_horarios_slot", table_name="enrollment_horarios")
    op.drop_table("enrollment_horarios")
    op.drop_index("ix_enrollments_paciente", table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index("ix_blackouts_periodo", table_name="blackouts")
    op.drop_table("blackouts")
    # ### end Alembic commands ###
