"""pacientes, servicos, pacotes e configuracao

Revision ID: 48835768d7f4
Revises: c9839d1c6ddd
Create Date: 2026-09-09 21:28:32.556584

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "48835768d7f4"
down_revision: str | None = "c9839d1c6ddd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuracao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cancelamento_antecedencia_horas", sa.Integer(), nullable=False),
        sa.Column("reposicao_exige_justificativa", sa.Boolean(), nullable=False),
        sa.Column("reposicao_prazo_mesmo_mes", sa.Boolean(), nullable=False),
        sa.Column("falta_consome_sessao_do_pacote", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_configuracao_linha_unica")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuracao")),
    )
    op.create_table(
        "horarios_funcionamento",
        sa.Column("dia_semana", sa.SmallInteger(), nullable=False),
        sa.Column("aberto", sa.Boolean(), nullable=False),
        sa.Column("hora_abertura", sa.Time(), nullable=False),
        sa.Column("hora_fechamento", sa.Time(), nullable=False),
        sa.Column("pausa_inicio", sa.Time(), nullable=True),
        sa.Column("pausa_fim", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(pausa_inicio IS NULL) = (pausa_fim IS NULL)",
            name=op.f("ck_horarios_funcionamento_pausa_completa"),
        ),
        sa.CheckConstraint(
            "NOT aberto OR hora_fechamento > hora_abertura",
            name=op.f("ck_horarios_funcionamento_janela_coerente"),
        ),
        sa.CheckConstraint(
            "dia_semana BETWEEN 0 AND 6", name=op.f("ck_horarios_funcionamento_dia_semana_valido")
        ),
        sa.PrimaryKeyConstraint("dia_semana", name=op.f("pk_horarios_funcionamento")),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome_completo", sa.String(length=160), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.Column("data_nascimento", sa.Date(), nullable=True),
        sa.Column("sexo", sa.String(length=16), nullable=False),
        sa.Column("estado_civil", sa.String(length=16), nullable=False),
        sa.Column("profissao", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("emergencia_nome", sa.String(length=160), nullable=True),
        sa.Column("emergencia_telefone", sa.String(length=20), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("consentimento_lgpd", sa.Boolean(), nullable=False),
        sa.Column("consentimento_em", sa.Date(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_index(op.f("ix_patients_nome_completo"), "patients", ["nome_completo"], unique=False)
    # Ajuste manual: CPF é opcional, então a unicidade tem de ser PARCIAL.
    # Um UNIQUE comum no Postgres aceita vários NULL (funcionaria), mas o
    # autogenerate não emite índice condicional — e queremos deixar explícito
    # que "sem CPF" nunca colide com "sem CPF".
    op.create_index(
        "ix_patients_cpf_unico",
        "patients",
        ["cpf"],
        unique=True,
        postgresql_where=sa.text("cpf IS NOT NULL"),
    )
    # Busca por nome sem diferenciar maiúsculas: a recepção digita "maria" e
    # o cadastro tem "Maria Silva". Sem este índice, o ILIKE varre a tabela.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "ix_patients_nome_trgm",
        "patients",
        [sa.text("lower(nome_completo) gin_trgm_ops")],
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_patients_telefone"), "patients", ["telefone"], unique=False)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("duracao_min", sa.Integer(), nullable=False),
        sa.Column("preco_centavos", sa.Integer(), nullable=False),
        sa.Column("capacidade_padrao", sa.Integer(), nullable=False),
        sa.Column("cor", sa.String(length=7), nullable=False),
        sa.Column("modelo_cobranca", sa.String(length=16), nullable=False),
        sa.Column("sugestao_pacote_sessoes", sa.Integer(), nullable=True),
        sa.Column("sugestao_pacote_validade_dias", sa.Integer(), nullable=True),
        sa.Column("sugestao_pacote_valor_centavos", sa.Integer(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "modelo_cobranca = 'pacote' OR ( sugestao_pacote_sessoes IS NULL AND sugestao_pacote_validade_dias IS NULL AND sugestao_pacote_valor_centavos IS NULL)",
            name=op.f("ck_services_sugestao_pacote_so_em_servico_de_pacote"),
        ),
        sa.CheckConstraint("capacidade_padrao > 0", name=op.f("ck_services_capacidade_positiva")),
        sa.CheckConstraint("duracao_min > 0", name=op.f("ck_services_duracao_positiva")),
        sa.CheckConstraint("preco_centavos >= 0", name=op.f("ck_services_preco_nao_negativo")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("nome", name=op.f("uq_services_nome")),
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("sessoes_contratadas", sa.Integer(), nullable=False),
        sa.Column("valor_centavos", sa.Integer(), nullable=False),
        sa.Column("validade_ate", sa.Date(), nullable=True),
        sa.Column("comprado_em", sa.Date(), nullable=False),
        sa.Column("registrado_por_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sessoes_contratadas > 0", name=op.f("ck_packages_sessoes_positivas")),
        sa.CheckConstraint("valor_centavos >= 0", name=op.f("ck_packages_valor_nao_negativo")),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_packages_patient_id_patients")
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por_id"], ["users.id"], name=op.f("fk_packages_registrado_por_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_packages_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
    )
    op.create_index(op.f("ix_packages_patient_id"), "packages", ["patient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_packages_patient_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_table("services")
    op.drop_index(op.f("ix_patients_telefone"), table_name="patients")
    op.drop_index("ix_patients_nome_trgm", table_name="patients")
    op.drop_index("ix_patients_cpf_unico", table_name="patients")
    op.drop_index(op.f("ix_patients_nome_completo"), table_name="patients")
    op.drop_table("patients")
    op.drop_table("horarios_funcionamento")
    op.drop_table("configuracao")
    # ### end Alembic commands ###
