"""cobrancas

Revision ID: 4bd39ca4db02
Revises: 42f493470451
Create Date: 2026-09-09 23:16:14.858639

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4bd39ca4db02"
down_revision: str | None = "42f493470451"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "mensalidade", "pacote", "avulsa", name="tipocobranca", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("descricao", sa.String(length=200), nullable=False),
        sa.Column("competencia_inicio", sa.Date(), nullable=True),
        sa.Column("competencia_fim", sa.Date(), nullable=True),
        sa.Column("valor_centavos", sa.Integer(), nullable=False),
        sa.Column("vencimento", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pendente", "pago", "cancelado", name="statuscobranca", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("pago_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "forma_pagamento",
            sa.Enum(
                "dinheiro",
                "pix",
                "debito",
                "credito",
                "transferencia",
                "outro",
                name="formapagamento",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("registrado_por_id", sa.Integer(), nullable=True),
        sa.Column("motivo_cancelamento", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'pago' OR pago_em IS NOT NULL", name=op.f("ck_charges_pago_tem_data")
        ),
        sa.CheckConstraint("valor_centavos >= 0", name=op.f("ck_charges_valor_nao_negativo")),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_charges_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["enrollments.id"], name=op.f("fk_charges_enrollment_id_enrollments")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_charges_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_charges_patient_id_patients")
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por_id"], ["users.id"], name=op.f("fk_charges_registrado_por_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charges")),
    )
    op.create_index(
        "ix_charges_mensalidade_por_ciclo",
        "charges",
        ["enrollment_id", "competencia_inicio"],
        unique=True,
        postgresql_where=sa.text("tipo = 'mensalidade' AND status <> 'cancelado'"),
    )
    op.create_index("ix_charges_paciente", "charges", ["patient_id", "status"], unique=False)
    op.create_index(
        "ix_charges_pacote_unico",
        "charges",
        ["package_id"],
        unique=True,
        postgresql_where=sa.text("tipo = 'pacote' AND status <> 'cancelado'"),
    )
    op.create_index(
        "ix_charges_status_vencimento", "charges", ["status", "vencimento"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_charges_status_vencimento", table_name="charges")
    op.drop_index(
        "ix_charges_pacote_unico",
        table_name="charges",
        postgresql_where=sa.text("tipo = 'pacote' AND status <> 'cancelado'"),
    )
    op.drop_index("ix_charges_paciente", table_name="charges")
    op.drop_index(
        "ix_charges_mensalidade_por_ciclo",
        table_name="charges",
        postgresql_where=sa.text("tipo = 'mensalidade' AND status <> 'cancelado'"),
    )
    op.drop_table("charges")
    # ### end Alembic commands ###
