"""remove prazo de cancelamento

Revision ID: 747621e78a61
Revises: 48835768d7f4
Create Date: 2026-09-09 22:00:43.748101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "747621e78a61"
down_revision: str | None = "48835768d7f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuracao", "cancelamento_antecedencia_horas")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuracao",
        sa.Column(
            "cancelamento_antecedencia_horas", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
