"""enums como varchar tipado, nao string crua

Revision ID: 8e6f53d3126d
Revises: a5d0bdc43ee4
Create Date: 2026-09-09 22:11:38.532437

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8e6f53d3126d"
down_revision: str | None = "a5d0bdc43ee4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookings",
        "origem",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "recorrente",
            "avulsa",
            "reposicao",
            "remarcacao",
            name="origemreserva",
            native_enum=False,
            length=32,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "agendada",
            "confirmada",
            "presente",
            "falta",
            "cancelada",
            name="statusreserva",
            native_enum=False,
            length=32,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "packages",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "ativo", "encerrado", "cancelado", name="statuspacote", native_enum=False, length=32
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "patients",
        "sexo",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "feminino",
            "masculino",
            "outro",
            "nao_informado",
            name="sexo",
            native_enum=False,
            length=32,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "patients",
        "estado_civil",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "solteiro",
            "casado",
            "divorciado",
            "viuvo",
            "uniao_estavel",
            "nao_informado",
            name="estadocivil",
            native_enum=False,
            length=32,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "modelo_cobranca",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum("mensalidade", "pacote", name="modelocobranca", native_enum=False, length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "agendada", "realizada", "cancelada", name="statussessao", native_enum=False, length=32
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "status",
        existing_type=sa.Enum(
            "agendada", "realizada", "cancelada", name="statussessao", native_enum=False, length=32
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "modelo_cobranca",
        existing_type=sa.Enum(
            "mensalidade", "pacote", name="modelocobranca", native_enum=False, length=32
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "patients",
        "estado_civil",
        existing_type=sa.Enum(
            "solteiro",
            "casado",
            "divorciado",
            "viuvo",
            "uniao_estavel",
            "nao_informado",
            name="estadocivil",
            native_enum=False,
            length=32,
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "patients",
        "sexo",
        existing_type=sa.Enum(
            "feminino",
            "masculino",
            "outro",
            "nao_informado",
            name="sexo",
            native_enum=False,
            length=32,
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "packages",
        "status",
        existing_type=sa.Enum(
            "ativo", "encerrado", "cancelado", name="statuspacote", native_enum=False, length=32
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "status",
        existing_type=sa.Enum(
            "agendada",
            "confirmada",
            "presente",
            "falta",
            "cancelada",
            name="statusreserva",
            native_enum=False,
            length=32,
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "origem",
        existing_type=sa.Enum(
            "recorrente",
            "avulsa",
            "reposicao",
            "remarcacao",
            name="origemreserva",
            native_enum=False,
            length=32,
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
