"""agenda: sessoes e reservas

Revision ID: a5d0bdc43ee4
Revises: 747621e78a61
Create Date: 2026-09-09 22:05:25.637468

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a5d0bdc43ee4"
down_revision: str | None = "747621e78a61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column("inicia_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("termina_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacidade", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacidade > 0", name=op.f("ck_sessions_capacidade_positiva")),
        sa.CheckConstraint("termina_em > inicia_em", name=op.f("ck_sessions_intervalo_coerente")),
        sa.ForeignKeyConstraint(
            ["professional_id"], ["users.id"], name=op.f("fk_sessions_professional_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_sessions_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index("ix_sessions_inicia_em", "sessions", ["inicia_em"], unique=False)
    op.create_index(
        "ix_sessions_instrutor_sem_conflito",
        "sessions",
        ["professional_id", "inicia_em"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelada'"),
    )
    op.create_index(
        "ix_sessions_profissional", "sessions", ["professional_id", "inicia_em"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("posicao", sa.SmallInteger(), nullable=False),
        sa.Column("capacidade_sessao", sa.SmallInteger(), nullable=False),
        sa.Column("origem", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("justificada", sa.Boolean(), nullable=False),
        sa.Column("motivo_justificativa", sa.Text(), nullable=True),
        sa.Column("substitui_booking_id", sa.Integer(), nullable=True),
        sa.Column("cancelado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_cancelamento", sa.Text(), nullable=True),
        sa.Column("criado_por_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'cancelada' OR cancelado_em IS NOT NULL",
            name=op.f("ck_bookings_cancelada_tem_data"),
        ),
        sa.CheckConstraint(
            "posicao <= capacidade_sessao", name=op.f("ck_bookings_posicao_dentro_da_capacidade")
        ),
        sa.CheckConstraint("posicao >= 1", name=op.f("ck_bookings_posicao_positiva")),
        sa.CheckConstraint(
            "substitui_booking_id IS NULL OR substitui_booking_id <> id",
            name=op.f("ck_bookings_nao_substitui_a_si_mesma"),
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"], ["users.id"], name=op.f("fk_bookings_criado_por_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_bookings_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_bookings_patient_id_patients")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_bookings_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["substitui_booking_id"],
            ["bookings.id"],
            name=op.f("fk_bookings_substitui_booking_id_bookings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.create_index("ix_bookings_paciente", "bookings", ["patient_id", "status"], unique=False)
    op.create_index(
        "ix_bookings_paciente_unico_na_sessao",
        "bookings",
        ["session_id", "patient_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelada'"),
    )
    op.create_index(
        "ix_bookings_posicao_unica",
        "bookings",
        ["session_id", "posicao"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelada'"),
    )
    op.create_index(op.f("ix_bookings_session_id"), "bookings", ["session_id"], unique=False)
    op.create_index(
        "ix_bookings_substitui_unico",
        "bookings",
        ["substitui_booking_id"],
        unique=True,
        postgresql_where=sa.text("substitui_booking_id IS NOT NULL AND status <> 'cancelada'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_bookings_substitui_unico",
        table_name="bookings",
        postgresql_where=sa.text("substitui_booking_id IS NOT NULL AND status <> 'cancelada'"),
    )
    op.drop_index(op.f("ix_bookings_session_id"), table_name="bookings")
    op.drop_index(
        "ix_bookings_posicao_unica",
        table_name="bookings",
        postgresql_where=sa.text("status <> 'cancelada'"),
    )
    op.drop_index(
        "ix_bookings_paciente_unico_na_sessao",
        table_name="bookings",
        postgresql_where=sa.text("status <> 'cancelada'"),
    )
    op.drop_index("ix_bookings_paciente", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_sessions_profissional", table_name="sessions")
    op.drop_index(
        "ix_sessions_instrutor_sem_conflito",
        table_name="sessions",
        postgresql_where=sa.text("status <> 'cancelada'"),
    )
    op.drop_index("ix_sessions_inicia_em", table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
