"""cria tabela de usuarios

Revision ID: c9839d1c6ddd
Revises: f5e0beae7f09
Create Date: 2026-09-08 21:53:05.184292

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9839d1c6ddd"
down_revision: str | None = "f5e0beae7f09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "papel", sa.Enum("admin", "recepcao", "instrutor", name="papel_usuario"), nullable=False
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # Ajuste manual: o autogenerate cria o tipo ENUM junto com a tabela, mas
    # não o remove no downgrade. Sem este DROP, um downgrade seguido de
    # upgrade falha com "type papel_usuario already exists".
    sa.Enum(name="papel_usuario").drop(op.get_bind(), checkfirst=True)
