"""estrutura inicial

Revision ID: f5e0beae7f09
Revises:
Create Date: 2026-09-08 19:10:23.992523

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f5e0beae7f09"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
